const Qs = [
  {q:"What does <code>typeof null</code> return in JavaScript?",opts:["null","undefined","object","boolean"],ans:2,tag:"Types",why:"This is a famous JS bug. <strong>typeof null === 'object'</strong> — a quirk from the language's first version that was kept for backward compatibility."},
  {q:"Which keyword declares a block-scoped variable that <em>can</em> be reassigned?",opts:["var","let","const","static"],ans:1,tag:"Variables",why:"<strong>let</strong> is block-scoped and reassignable. <strong>const</strong> is block-scoped but not reassignable. <strong>var</strong> is function-scoped and hoisted."},
  {q:"What does <code>console.log(0.1 + 0.2 === 0.3)</code> output?",opts:["true","false","NaN","ReferenceError"],ans:1,tag:"Numbers",why:"JavaScript uses IEEE 754 floating-point math. <strong>0.1 + 0.2</strong> equals <strong>0.30000000000000004</strong>, not exactly 0.3 — so the comparison is false."},
  {q:"Which array method returns a <strong>new</strong> array of elements that pass a test?",opts:["forEach","map","filter","reduce"],ans:2,tag:"Arrays",why:"<strong>filter()</strong> returns a new array with only the elements for which the callback returns true. <code>map</code> transforms, <code>forEach</code> iterates with no return."},
  {q:"What does the <code>===</code> (strict equality) operator check?",opts:["Value only","Type only","Value and type","Memory address"],ans:2,tag:"Operators",why:"<strong>===</strong> checks both value and type without coercion. <code>==</code> coerces types, so <code>'3' == 3</code> is true but <code>'3' === 3</code> is false."},
  {q:"What is hoisting in JavaScript?",opts:["Moving imports to the top","Declarations moved to top of scope before execution","Copying variables into memory","Deleting variables after use"],ans:1,tag:"Scope",why:"<strong>Hoisting</strong> moves variable and function declarations to the top of their scope before code executes. Variables with <code>var</code> are hoisted but not initialized."},
  {q:"Which of these is <em>NOT</em> a falsy value in JavaScript?",opts:["0","'' (empty string)","'false' (non-empty string)","null"],ans:2,tag:"Types",why:"The string <strong>'false'</strong> is truthy — it's a non-empty string. Falsy values: <code>false</code>, <code>0</code>, <code>''</code>, <code>null</code>, <code>undefined</code>, <code>NaN</code>."},
  {q:"What does <code>Array.isArray([])</code> return?",opts:["false","true","undefined","NaN"],ans:1,tag:"Arrays",why:"<strong>Array.isArray()</strong> is the reliable way to check for arrays. <code>typeof []</code> returns 'object', making it unreliable for this purpose."},
  {q:"What is a closure in JavaScript?",opts:["A loop that never ends","A function that retains access to its outer scope's variables","A method to close the browser tab","A way to exit a function early"],ans:1,tag:"Functions",why:"A <strong>closure</strong> is a function that retains access to its lexical scope even when executed outside that scope — foundational to modules and memoization."},
  {q:"Which method converts a JSON string into a JavaScript object?",opts:["JSON.stringify()","JSON.parse()","JSON.convert()","JSON.decode()"],ans:1,tag:"JSON",why:"<strong>JSON.parse()</strong> converts a JSON string → JS object. <strong>JSON.stringify()</strong> does the reverse: JS object → JSON string."},
];

const KEYS = ['A','B','C','D'];
const TOTAL_TIME = 100;